# 교차 검증과 그리드 서치

In [1]:
import pandas as pd
wine=pd.read_csv('https://bit.ly/wine_csv_data')

In [2]:
data=wine[['alcohol','sugar','pH']].to_numpy()
target=wine['class'].to_numpy()

In [4]:
from sklearn.model_selection import train_test_split
train_input,test_input,train_target,test_target=train_test_split(data,target,test_size=0.2,random_state=42)

In [5]:
sub_input,val_input,sub_target,val_target=train_test_split(train_input,train_target,test_size=0.2,random_state=42)

In [6]:
print(sub_input.shape,val_input.shape)

(4157, 3) (1040, 3)


In [7]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier(random_state=42)
dt.fit(sub_input,sub_target)
print(dt.score(sub_input,sub_target))
print(dt.score(val_input,val_target))

0.9971133028626413
0.864423076923077


In [10]:
from sklearn.model_selection import cross_validate
scores=cross_validate(dt,train_input,train_target)
print(scores)

{'fit_time': array([0.00629163, 0.00655818, 0.00661278, 0.00622439, 0.00597358]), 'score_time': array([0.00099492, 0.00141597, 0.00123072, 0.00080323, 0.00094891]), 'test_score': array([0.86923077, 0.84615385, 0.87680462, 0.84889317, 0.83541867])}


In [9]:
from sklearn.model_selection import cross_val_score
scores=cross_val_score(dt,train_input,train_target)
print(scores)

[0.86923077 0.84615385 0.87680462 0.84889317 0.83541867]


In [11]:
import numpy as np
print(np.mean(scores['test_score']))

0.855300214703487


In [12]:
from sklearn.model_selection import StratifiedKFold
scores=cross_validate(dt,train_input,train_target,cv=StratifiedKFold())
print(np.mean(scores['test_score']))

0.855300214703487


In [15]:
splitter=StratifiedKFold(n_splits=10,shuffle=True,random_state=42)
scores=cross_validate(dt,train_input,train_target,cv=splitter)
print(np.mean(scores['test_score']))

0.8574181117533719


In [16]:
from sklearn.model_selection import GridSearchCV
params={'min_impurity_decrease':[0.0001,0.0002,0.0003,0.0004,0.0005,]}

In [19]:
gs=GridSearchCV(DecisionTreeClassifier(random_state=42),params,n_jobs=-1)
#여기서 n_job는 cpu의 코어를 어떻게 줄 거냐? -1이면 그냥 전체 선택
#파라미터는 5개이고 cv는 기본적으로 5여서 (5fold)총 25개 연산

In [ ]:
gs.fit(train_input,train_target)
"""

그러니까, 훈련 검증 테스트 이렇게 나누고
최적의 하이퍼 파라미터를 찾으면
그 후
훈련+검증 이렇게 다시 싹 모델을 훈련해야 함

"""

GridSearchCV(estimator=DecisionTreeClassifier(random_state=42), n_jobs=-1,
             param_grid={'min_impurity_decrease': [0.0001, 0.0002, 0.0003,
                                                   0.0004, 0.0005]})

In [24]:
dt=gs.best_estimator_
print(dt.score(train_input,train_target))
print(dt.score(test_input,test_target))

0.9615162593804117
0.8653846153846154


In [22]:
print(gs.best_params_)

{'min_impurity_decrease': 0.0001}


In [23]:
print(gs.cv_results_['mean_test_score'])

[0.86819297 0.86453617 0.86492226 0.86780891 0.86761605]


In [25]:
best_index=np.argmax(gs.cv_results_['mean_test_score'])
print(gs.cv_results_['params'][best_index])

{'min_impurity_decrease': 0.0001}


In [27]:
gs.cv_results_

{'mean_fit_time': array([0.00766478, 0.00818233, 0.00764284, 0.00785766, 0.00581889]),
 'std_fit_time': array([0.00106639, 0.00130099, 0.00174591, 0.00312153, 0.00104203]),
 'mean_score_time': array([0.00132065, 0.00167894, 0.00219731, 0.00126576, 0.00125647]),
 'std_score_time': array([0.00011183, 0.00042098, 0.00072131, 0.00033947, 0.00032089]),
 'param_min_impurity_decrease': masked_array(data=[0.0001, 0.0002, 0.0003, 0.0004, 0.0005],
              mask=[False, False, False, False, False],
        fill_value=1e+20),
 'params': [{'min_impurity_decrease': 0.0001},
  {'min_impurity_decrease': 0.0002},
  {'min_impurity_decrease': 0.0003},
  {'min_impurity_decrease': 0.0004},
  {'min_impurity_decrease': 0.0005}],
 'split0_test_score': array([0.86923077, 0.87115385, 0.86923077, 0.86923077, 0.86538462]),
 'split1_test_score': array([0.86826923, 0.86346154, 0.85961538, 0.86346154, 0.86923077]),
 'split2_test_score': array([0.8825794 , 0.87680462, 0.87584216, 0.88161694, 0.8825794 ]),
 'spli

In [33]:
params={
    'min_impurity_decrease':np.arange(0.0001,0.001,0.0001),
    'max_depth':range(5,20,1),
    'min_samples_split':range(2,100,10)
}
"""
넘파이의 어레인지는 배열을 만들고
range는 정수! 근데 객체를 만드는.
정수는 메모리를 아끼든 + 그리고 의도를 보여준대 정수로 할 수 있으면 최대한 range로 쓰는 게 좋을 듯
"""

'\n넘파이의 어레인지는 배열을 만들고\nrange는 정수! 근데 객체를 만드는.\n정수는 메모리를 아끼든 + 그리고 의도를 보여준대 정수로 할 수 있으면 최대한 range로 쓰는 게 좋을 듯\n'

In [34]:
gs=GridSearchCV(DecisionTreeClassifier(random_state=42),params,n_jobs=-1)
gs.fit(train_input,train_target)

GridSearchCV(estimator=DecisionTreeClassifier(random_state=42), n_jobs=-1,
             param_grid={'max_depth': range(5, 20),
                         'min_impurity_decrease': array([0.0001, 0.0002, 0.0003, 0.0004, 0.0005, 0.0006, 0.0007, 0.0008,
       0.0009]),
                         'min_samples_split': range(2, 100, 10)})

In [35]:
print(gs.best_params_)

{'max_depth': 14, 'min_impurity_decrease': np.float64(0.0004), 'min_samples_split': 12}


In [36]:
print(np.max(gs.cv_results_['mean_test_score']))

0.8683865773302731


In [37]:
from scipy.stats import uniform,randint

In [51]:
rgen=randint(0,10)
rgen.rvs(10)

array([8, 2, 7, 5, 2, 1, 8, 1, 1, 3])

In [52]:
np.unique(rgen.rvs(1000),return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([107,  95, 102, 102,  89,  95, 112,  86, 110, 102]))

In [53]:
ugen=uniform(0,1)
ugen.rvs(10)

array([0.52742758, 0.7709463 , 0.01992201, 0.39383208, 0.1373284 ,
       0.34205698, 0.61242515, 0.80386705, 0.52225535, 0.21750642])

In [54]:
params={
    'min_impurity_decrease':uniform(0.0001,0.001),
    'max_depth':randint(20,50),
    'min_samples_split':randint(2,25),
    'min_samples_leaf':randint(1,25),
}

In [55]:
from sklearn.model_selection import RandomizedSearchCV
gs=RandomizedSearchCV(DecisionTreeClassifier(random_state=42),params,n_iter=100,n_jobs=-1,random_state=42)
gs.fit(train_input,train_target)

RandomizedSearchCV(estimator=DecisionTreeClassifier(random_state=42),
                   n_iter=100, n_jobs=-1,
                   param_distributions={'max_depth': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000023A344FB380>,
                                        'min_impurity_decrease': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x0000023A345E6E90>,
                                        'min_samples_leaf': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000023A344F9A50>,
                                        'min_samples_split': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000023A344FA0D0>},
                   random_state=42)

In [56]:
print(gs.best_params_)

{'max_depth': 39, 'min_impurity_decrease': np.float64(0.00034102546602601173), 'min_samples_leaf': 7, 'min_samples_split': 13}


In [57]:
print(np.max(gs.cv_results_['mean_test_score']))

0.8695428296438884


In [58]:
dt=gs.best_estimator_
print(dt.score(test_input,test_target))

0.86


In [59]:
gs=RandomizedSearchCV(DecisionTreeClassifier(random_state=42,splitter='random'),params,n_iter=100,n_jobs=-1,random_state=42)
gs.fit(train_input,train_target)

RandomizedSearchCV(estimator=DecisionTreeClassifier(random_state=42,
                                                    splitter='random'),
                   n_iter=100, n_jobs=-1,
                   param_distributions={'max_depth': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000023A344FB380>,
                                        'min_impurity_decrease': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x0000023A345E6E90>,
                                        'min_samples_leaf': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000023A344F9A50>,
                                        'min_samples_split': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000023A344FA0D0>},
                   random_state=42)

In [60]:
print(np.max(gs.cv_results_['mean_test_score']))

0.8458726956392981


In [61]:
dt=gs.best_estimator_
print(dt.score(test_input,test_target))

0.786923076923077
